#include <kernel.h>

uint64_t kmain(struct bootinfo *bootinfo){
	KDEBUG("ARCH "ARCH);
	KDEBUG("FB %dx%d at 0x%x (%d MB)", fb.width, fb.height, fb.buffer, BYTES_TO_MB(fb.size));
	KDEBUG("Available system memory %d MB", BYTES_TO_MB(heap.n_block*HEAP_BLOCK_SIZE));
	graphics_pixel sprite_px[] = {
		GRAPHICS_PIXEL_RED,   GRAPHICS_PIXEL_BLUE,   GRAPHICS_PIXEL_GREEN, GRAPHICS_PIXEL_BLACK, GRAPHICS_PIXEL_GRAY, GRAPHICS_PIXEL_WHITE, GRAPHICS_PIXEL_BLACK, GRAPHICS_PIXEL_BLACK,
		GRAPHICS_PIXEL_RED,   GRAPHICS_PIXEL_BLUE,   GRAPHICS_PIXEL_GREEN, GRAPHICS_PIXEL_BLACK, GRAPHICS_PIXEL_GRAY, GRAPHICS_PIXEL_WHITE, GRAPHICS_PIXEL_BLACK, GRAPHICS_PIXEL_BLACK,
		GRAPHICS_PIXEL_RED,   GRAPHICS_PIXEL_BLUE,   GRAPHICS_PIXEL_GREEN, GRAPHICS_PIXEL_BLACK, GRAPHICS_PIXEL_GRAY, GRAPHICS_PIXEL_WHITE, GRAPHICS_PIXEL_BLACK, GRAPHICS_PIXEL_BLACK,
		GRAPHICS_PIXEL_RED,   GRAPHICS_PIXEL_BLUE,   GRAPHICS_PIXEL_GREEN, GRAPHICS_PIXEL_BLACK, GRAPHICS_PIXEL_GRAY, GRAPHICS_PIXEL_WHITE, GRAPHICS_PIXEL_BLACK, GRAPHICS_PIXEL_BLACK,
		GRAPHICS_PIXEL_RED,   GRAPHICS_PIXEL_BLUE,   GRAPHICS_PIXEL_GREEN, GRAPHICS_PIXEL_BLACK, GRAPHICS_PIXEL_GRAY, GRAPHICS_PIXEL_WHITE, GRAPHICS_PIXEL_BLACK, GRAPHICS_PIXEL_BLACK,
		GRAPHICS_PIXEL_RED,   GRAPHICS_PIXEL_BLUE,   GRAPHICS_PIXEL_GREEN, GRAPHICS_PIXEL_BLACK, GRAPHICS_PIXEL_GRAY, GRAPHICS_PIXEL_WHITE, GRAPHICS_PIXEL_BLACK, GRAPHICS_PIXEL_BLACK,
		GRAPHICS_PIXEL_RED,   GRAPHICS_PIXEL_BLUE,   GRAPHICS_PIXEL_GREEN, GRAPHICS_PIXEL_BLACK, GRAPHICS_PIXEL_GRAY, GRAPHICS_PIXEL_WHITE, GRAPHICS_PIXEL_BLACK, GRAPHICS_PIXEL_BLACK,
		GRAPHICS_PIXEL_RED,   GRAPHICS_PIXEL_BLUE,   GRAPHICS_PIXEL_GREEN, GRAPHICS_PIXEL_BLACK, GRAPHICS_PIXEL_GRAY, GRAPHICS_PIXEL_WHITE, GRAPHICS_PIXEL_BLACK, GRAPHICS_PIXEL_BLACK,

	};
	graphics_sprite sprite = {
		.height = 8,
		.width = 8,
		.pixels = sprite_px,
	};
	while(1){
		for(uint8_t i = 0; i <= 0xff; i++){
			framebuffer_clear(&fb, &(framebuffer_pixel){.Green = 0xaa , .Blue = 0xaa+i , .Red = 0xaa , .Alpha = 0x0 });
			framebuffer_draw_sprite(&fb, fb.width/2 - sprite.width/2, fb.height/2 - sprite.height/2, &sprite);
			framebuffer_update_device(&fb);
		}
	}
	kprint("Welcome to l00n1x !\n");	
	shell();
	while(1){
		/* we cannot return since we switched the stack */
	}
	return 0xcafe;
}
