#ifndef _VM_GRAMMAR_H
#define _VM_GRAMMAR_H

#define VM_END_SENTENCE ";"

#define VM_TYPE_NAME "[a-zA-Z,_]{1}[a-zA-Z0-9,_]*\\s*\\**"
#define VM_VARIABLE_NAME "[a-zA-Z,_]{1}[a-zA-Z0-9,_]*"
#define VM_FN_NAME VM_VARIABLE_NAME
#define VM_FN_RET_TYPE VM_TYPE_NAME

#define VM_UINT_VALUE "[0-9]{1}[0-9]*"
#define VM_STRING_VALUE "\".{1}.*\""

#define VM_UINT_ASSIGNMENT "\\s*"VM_VARIABLE_NAME"\\s*=\\s*"VM_UINT_VALUE"\\s*"VM_END_SENTENCE
#define VM_UINT_DECLARATION "\\s*"VM_TYPE_NAME VM_UINT_ASSIGNMENT

#define VM_STRING_ASSIGNMENT "\\s*"VM_VARIABLE_NAME"\\s*=\\s*"VM_STRING_VALUE"\\s*"VM_END_SENTENCE
#define VM_STRING_DECLARATION "\\s*"VM_TYPE_NAME VM_STRING_ASSIGNMENT

#define VM_VARIABLE_TO_VARIABLE_ASSIGNMENT "\\s*"VM_VARIABLE_NAME"\\s*=\\s*"VM_VARIABLE_NAME"\\s*"VM_END_SENTENCE
#define VM_VARIABLE_TO_VARIABLE_DECLARATION "\\s*"VM_TYPE_NAME VM_VARIABLE_TO_VARIABLE_ASSIGNMENT

#define VM_FN_DEFINITION "\\s*"VM_FN_RET_TYPE "\\s*" VM_FN_NAME "\\s*\\(.*\\)\\s*\\{.*\\}"

#endif
