#ifndef _PYTHONIX_GRAMMAR_H
#define _PYTHONIX_GRAMMAR_H

#define PYTHONIX_REGEX_INT "-?[0-9]{1}[0-9]*"
#define PYTHONIX_REGEX_STR "\".*\""
#define PYTHONIX_REGEX_VAR_NAME "[a-zA-Z,_]{1}[a-zA-Z0-9,_]*"
#define PYTHONIX_REGEX_FN_NAME PYTHONIX_REGEX_VAR_NAME
#define PYTHONIX_REGEX_ASSIGN "("PYTHONIX_REGEX_VAR_NAME")\\s*=\\s*"
#define PYTHONIX_REGEX_ASSIGN_STR PYTHONIX_REGEX_ASSIGN"("PYTHONIX_REGEX_STR")\\s*"
#define PYTHONIX_REGEX_ASSIGN_INT PYTHONIX_REGEX_ASSIGN"("PYTHONIX_REGEX_INT")\\s*"

#endif
