#ifndef _PYTHONIX_GRAMMAR_H
#define _PYTHONIX_GRAMMAR_H

#define PYTHONIX_REGEX_INT "-?[0-9]{1}[0-9]*"
#define PYTHONIX_REGEX_STR "[\",\'].*[\",\']"
#define PYTHONIX_REGEX_VAR_NAME "[a-zA-Z,_]{1}[a-zA-Z0-9,_]*"
#define PYTHONIX_REGEX_FN_NAME PYTHONIX_REGEX_VAR_NAME
#define PYTHONIX_REGEX_METHOD_NAME PYTHONIX_REGEX_FN_NAME

#define PYTHONIX_REGEX_VAR_OPERATOR_ANY "("PYTHONIX_REGEX_VAR_NAME")\\s*([+,\\-,\\*,/])=(.*)\n"

#define PYTHONIX_REGEX_ASSIGN "("PYTHONIX_REGEX_VAR_NAME")\\s*="
#define PYTHONIX_REGEX_ASSIGN_ANY PYTHONIX_REGEX_ASSIGN"(.*)\n"

#define PYTHONIX_REGEX_PRINT_VAR "("PYTHONIX_REGEX_VAR_NAME")\\s*\n"
#define PYTHONIX_REGEX_PRINT_VAR_NAME_GROUP 1

#define PYTHONIX_REGEX_FN_DEF "def\\s*("PYTHONIX_REGEX_FN_NAME")\\s*(\\(.*\\)):\n"
#define PYTHONIX_REGEX_FN_CALL "("PYTHONIX_REGEX_FN_NAME")\\s*(\\(.*\\))\n"

#define PYTHONIX_REGEX_METHOD_CALL "("PYTHONIX_REGEX_VAR_NAME").\\s*("PYTHONIX_REGEX_METHOD_NAME")\\s*(\\(.*\\))\n"
#define PYTHONIX_REGEX_METHOD_CALL_VAR_NAME_GROUP 1
#define PYTHONIX_REGEX_METHOD_CALL_METHOD_NAME_GROUP 2
#define PYTHONIX_REGEX_METHOD_CALL_METHOD_ARGS_GROUP 3

#endif
