#ifndef _PYTHONIX_GRAMMAR_H
#define _PYTHONIX_GRAMMAR_H

#define PYTHONIX_REGEX_INT "-?[0-9]{1}[0-9]*"
#define PYTHONIX_REGEX_STR "[\",\'].*[\",\']"
#define PYTHONIX_REGEX_VAR_NAME "[a-zA-Z,_]{1}[a-zA-Z0-9,_,.]*"
#define PYTHONIX_REGEX_FN_NAME PYTHONIX_REGEX_VAR_NAME

#define PYTHONIX_REGEX_VAR_ADD "("PYTHONIX_REGEX_VAR_NAME")\\s*+=\\s*"
#define PYTHONIX_REGEX_VAR_ADD_INT PYTHONIX_REGEX_VAR_ADD"("PYTHONIX_REGEX_INT")\\s*\n"
#define PYTHONIX_REGEX_VAR_ADD_INT_NAME_GROUP 1
#define PYTHONIX_REGEX_VAR_ADD_INT_VAL_GROUP 2

#define PYTHONIX_REGEX_VAR_ADD_STR PYTHONIX_REGEX_VAR_ADD"("PYTHONIX_REGEX_STR")\\s*\n"
#define PYTHONIX_REGEX_VAR_ADD_STR_NAME_GROUP 1
#define PYTHONIX_REGEX_VAR_ADD_STR_VAL_GROUP 2


#define PYTHONIX_REGEX_ASSIGN "("PYTHONIX_REGEX_VAR_NAME")\\s*=\\s*"
#define PYTHONIX_REGEX_ASSIGN_STR PYTHONIX_REGEX_ASSIGN"("PYTHONIX_REGEX_STR")\\s*\n"
#define PYTHONIX_REGEX_ASSIGN_STR_NAME_GROUP 1
#define PYTHONIX_REGEX_ASSIGN_STR_VAL_GROUP 2

#define PYTHONIX_REGEX_ASSIGN_INT PYTHONIX_REGEX_ASSIGN"("PYTHONIX_REGEX_INT")\\s*\n"
#define PYTHONIX_REGEX_ASSIGN_INT_NAME_GROUP 1
#define PYTHONIX_REGEX_ASSIGN_INT_VAL_GROUP 2

#define PYTHONIX_REGEX_ASSIGN_VAR PYTHONIX_REGEX_ASSIGN"("PYTHONIX_REGEX_VAR_NAME")\\s*\n"
#define PYTHONIX_REGEX_ASSIGN_VAR_NAME_GROUP 1
#define PYTHONIX_REGEX_ASSIGN_VAR_VAL_GROUP 2

#define PYTHONIX_REGEX_PRINT_VAR "("PYTHONIX_REGEX_VAR_NAME")\\s*\n"
#define PYTHONIX_REGEX_PRINT_VAR_NAME_GROUP 1

#define PYTHONIX_REGEX_FN_DEF "def\\s*("PYTHONIX_REGEX_FN_NAME")\\s*(\\(.*\\)):\n"
#define PYTHONIX_REGEX_FN_CALL "("PYTHONIX_REGEX_FN_NAME")\\s*(\\(.*\\))\n"
#endif
